// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6Sh_l53UNjcQURraWR8SDpEnm0GMxa8',
    appId: '1:391463711931:android:bfa54ce610bb723abce59e',
    messagingSenderId: '391463711931',
    projectId: 'access-ef167',
    storageBucket: 'access-ef167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfcmrtMHteEMMSNLkVYMQTH7_LKrMd_Gc',
    appId: '1:391463711931:ios:f3f07e44c61d10f5bce59e',
    messagingSenderId: '391463711931',
    projectId: 'access-ef167',
    storageBucket: 'access-ef167.appspot.com',
    iosBundleId: 'com.example.secureAccesss',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhitvLZJgjlkoCQENoZg_8A2BXtPL5vSw',
    appId: '1:391463711931:web:32dd3565d31f5c4ebce59e',
    messagingSenderId: '391463711931',
    projectId: 'access-ef167',
    authDomain: 'access-ef167.firebaseapp.com',
    storageBucket: 'access-ef167.appspot.com',
    measurementId: 'G-3TLGPGYMZQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfcmrtMHteEMMSNLkVYMQTH7_LKrMd_Gc',
    appId: '1:391463711931:ios:13a85a8c289efdcabce59e',
    messagingSenderId: '391463711931',
    projectId: 'access-ef167',
    storageBucket: 'access-ef167.appspot.com',
    iosBundleId: 'com.example.secureAccess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhitvLZJgjlkoCQENoZg_8A2BXtPL5vSw',
    appId: '1:391463711931:web:550b4c7650237727bce59e',
    messagingSenderId: '391463711931',
    projectId: 'access-ef167',
    authDomain: 'access-ef167.firebaseapp.com',
    storageBucket: 'access-ef167.appspot.com',
    measurementId: 'G-W20373HXBR',
  );

}